---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
  eslint:
    enabled: true
    channel: 'eslint-5'
  fixme:
    enabled: true
checks:
  method-complexity:
    config:
      threshold: 10
  return-statements:
    config:
      threshold: 6
ratings:
  paths:
    - '**.ts'
exclude_paths:
  - '.temp/'
  - 'config/'
  - 'dist/'
  - 'doc-themes/'
  - 'scripts/'
  - '**/*.test.ts'
  - '**/node_modules/'
